services:
  postgres_users_db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=as_users_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data_user_db'

volumes:
  postgres_data: