server:
  port: 8888

spring:
    application:
        name: config-server
    cloud:
        config:
          server:
            git:
              uri: https://github.com/MarcosLM11/learning-AI-platform-config.git
              default-label: main
              username: ${GITHUB_USERNAME}
              password: ${GITHUB_TOKEN}
              clone-on-start: true
